Repository codestates-seb/seb40_main_026, pull requests merged in 2022-11, with the labels that each got.

#2 ✨ feat:exception 기능 구현
  .github/pull_request_template.md
  .gitignore
  README.md
  server/HELP.md
  server/build.gradle
  server/gradle/wrapper/gradle-wrapper.properties
  server/gradlew
  server/gradlew.bat
  server/settings.gradle
  server/src/main/java/seb40main026/mainproject/MainProjectApplication.java
  server/src/main/java/seb40main026/mainproject/advice/GlobalExceptionAdvice.java
  server/src/main/java/seb40main026/mainproject/exception/BusinessException.java
  server/src/main/java/seb40main026/mainproject/exception/ExceptionCode.java
  server/src/main/java/seb40main026/mainproject/response/ErrorResponse.java
  server/src/main/resources/application.yml
  server/src/test/java/seb40main026/mainproject/MainProjectApplicationTests.java
Labels: enhancement

#12 [Server] :sparkles: feat: boast 게시판 CRUD + 좋아요 기능 구현
  server/src/main/generated/seb40main026/mainproject/boast/mapper/BoastMapperImpl.java
  server/src/main/java/seb40main026/mainproject/boast/controller/BoastController.java
  server/src/main/java/seb40main026/mainproject/boast/dto/BoastDto.java
  server/src/main/java/seb40main026/mainproject/boast/entity/Boast.java
  server/src/main/java/seb40main026/mainproject/boast/mapper/BoastMapper.java
  server/src/main/java/seb40main026/mainproject/boast/repository/BoastRepository.java
  server/src/main/java/seb40main026/mainproject/boast/service/BoastService.java
  server/src/main/java/seb40main026/mainproject/boastLike/entity/BoastLike.java
  server/src/main/java/seb40main026/mainproject/boastLike/repository/BoastLikeRepository.java
  server/src/main/java/seb40main026/mainproject/boastLike/service/BoastLikeService.java
Labels: BE

#19 [Client] ✨ feat: 좋아요 버튼 생성
  client/src/App.js
  client/src/assets/images/example.js
  client/src/assets/images/heart.png
  client/src/assets/images/top3.png
  client/src/components/LikeButton.js
  client/src/components/layout/Card.js
  client/src/components/layout/Footer/Footer.js
  client/src/pages/Boast.js
Labels: FE

#21 Feat/fe/question
  client/.eslintrc.json
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/QuestionView/Answer.js
  client/src/components/QuestionView/AnswerCreate.js
  client/src/components/QuestionView/QuestionView.js
  client/src/components/QuestionsList/QuesSearch.js
  client/src/components/QuestionsList/QuestionList.js
  client/src/components/QuestionsList/QuestionsHeader.js
  client/src/components/QuestionsList/QuestionsMain.js
  client/src/components/QuestionsList/Questionsfilter.js
Labels: FE

#18 [Server] ✨ feat: question CRUD, like, report 기능 구현
  server/src/main/java/seb40main026/mainproject/question/controller/QuestionController.java
  server/src/main/java/seb40main026/mainproject/question/dto/QuestionDto.java
  server/src/main/java/seb40main026/mainproject/question/dto/QuestionLikeResponseDto.java
  server/src/main/java/seb40main026/mainproject/question/dto/QuestionReportResponseDto.java
  server/src/main/java/seb40main026/mainproject/question/entity/Question.java
  server/src/main/java/seb40main026/mainproject/question/entity/QuestionLike.java
  server/src/main/java/seb40main026/mainproject/question/entity/QuestionReport.java
  server/src/main/java/seb40main026/mainproject/question/mapper/QuestionMapper.java
  server/src/main/java/seb40main026/mainproject/question/repository/QuestionLikeRepository.java
  server/src/main/java/seb40main026/mainproject/question/repository/QuestionReportRepository.java
  server/src/main/java/seb40main026/mainproject/question/repository/QuestionRepository.java
  server/src/main/java/seb40main026/mainproject/question/service/QuestionService.java
Labels: BE

#23 [Client]  🎨 : style : 좋아요버튼 스타일 수정
  client/src/assets/images/heart.png
  client/src/components/LikeButton.js
  client/src/components/Shared/LikeButton.js
  client/src/components/layout/Card.js
Labels: FE

#22 [Server] ✨ feat: boast / reply 기능 구현 완료
  server/src/main/generated/seb40main026/mainproject/boast/mapper/BoastMapperImpl.java
  server/src/main/java/seb40main026/mainproject/boast/controller/BoastController.java
  server/src/main/java/seb40main026/mainproject/boast/dto/BoastDto.java
  server/src/main/java/seb40main026/mainproject/boast/entity/Boast.java
  server/src/main/java/seb40main026/mainproject/boast/service/BoastService.java
  server/src/main/java/seb40main026/mainproject/boastLike/service/BoastLikeService.java
  server/src/main/java/seb40main026/mainproject/boastReply/controller/BoastReplyController.java
  server/src/main/java/seb40main026/mainproject/boastReply/dto/BoastReplyDto.java
  server/src/main/java/seb40main026/mainproject/boastReply/entity/BoastReply.java
  server/src/main/java/seb40main026/mainproject/boastReply/mapper/BoastReplyMapper.java
  server/src/main/java/seb40main026/mainproject/boastReply/repository/BoastReplyRepository.java
  server/src/main/java/seb40main026/mainproject/boastReply/service/BoastReplyService.java
  server/src/main/java/seb40main026/mainproject/exception/ExceptionCode.java
  server/src/main/resources/application.yml
Labels: BE

#24 [Client]:sparkle: feat: 로그인페이지 구현 외
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/api/example.js
  client/src/assets/images/profile.png
  client/src/components/Login/Login.js
  client/src/components/Login/SocialLogin.js
  client/src/components/Signup/Signup.js
  client/src/components/layout/Footer/Footer.js
  client/src/components/layout/Header/Header.js
  client/src/components/layout/Header/HeaderHamburgerModal.js
  client/src/components/layout/Header/HeaderProfile.js
  client/src/components/layout/Header/HeaderProfileModal.js
  client/src/components/shared/HorizonLine.js
  client/src/components/shared/MediumButton.js
  client/src/components/shared/SelectButton.js
  client/src/hooks/example.js
  client/src/pages/Boast.js
  client/src/pages/Loginpage.js
  client/src/pages/SignupPage.js
  client/src/styles/GlobalStyle.js
  client/src/utils/example.js
Labels: FE

#30 [Clinet]  ✨: feat : 자랑하기 리스트 페이지 구현
  client/src/assets/images/top3.png
  client/src/components/Boast/Card.js
  client/src/components/Shared/LikeButton.js
  client/src/pages/Boast.js
Labels: FE

#32 [Server] ✨ feat: Answer CRUD, like, report 기능 구현
  server/src/main/generated/seb40main026/mainproject/answer/mapper/AnswerMapperImpl.java
  server/src/main/java/seb40main026/mainproject/answer/controller/AnswerController.java
  server/src/main/java/seb40main026/mainproject/answer/dto/AnswerDto.java
  server/src/main/java/seb40main026/mainproject/answer/dto/AnswerLikeResponseDto.java
  server/src/main/java/seb40main026/mainproject/answer/dto/AnswerReportResponseDto.java
  server/src/main/java/seb40main026/mainproject/answer/entity/Answer.java
  server/src/main/java/seb40main026/mainproject/answer/entity/AnswerLike.java
  server/src/main/java/seb40main026/mainproject/answer/entity/AnswerReport.java
  server/src/main/java/seb40main026/mainproject/answer/mapper/AnswerMapper.java
  server/src/main/java/seb40main026/mainproject/answer/repository/AnswerLikeRepository.java
  server/src/main/java/seb40main026/mainproject/answer/repository/AnswerReportRepository.java
  server/src/main/java/seb40main026/mainproject/answer/repository/AnswerRepository.java
  server/src/main/java/seb40main026/mainproject/answer/service/AnswerService.java
  server/src/main/java/seb40main026/mainproject/exception/ExceptionCode.java
Labels: BE

#33 [Server] :sparkles: feat: image 업로드 구현 및 checkLike 구현
  server/src/main/java/seb40main026/mainproject/boast/controller/BoastController.java
  server/src/main/java/seb40main026/mainproject/boast/dto/BoastDto.java
  server/src/main/java/seb40main026/mainproject/boast/entity/Boast.java
  server/src/main/java/seb40main026/mainproject/boastLike/service/BoastLikeService.java
  server/src/main/java/seb40main026/mainproject/boastReply/service/BoastReplyService.java
  server/src/main/java/seb40main026/mainproject/exception/ExceptionCode.java
  server/src/main/java/seb40main026/mainproject/image/controller/imageController.java
  server/src/main/java/seb40main026/mainproject/image/entity/Image.java
  server/src/main/java/seb40main026/mainproject/image/repository/ImageRepository.java
  server/src/main/java/seb40main026/mainproject/image/service/ImageService.java
  server/src/main/resources/application.yml
Labels: BE

#42 [client]✨feat:회원정보 수정 페이지 구현, 🎨 style: 전반적인 CSS수정 및 상세 페이지 컴포넌트 분리
  client/src/App.js
  client/src/components/CommentCreate.js
  client/src/components/Commentlist.js
  client/src/components/Mypage/Mypage.js
  client/src/components/Mypage/MypageEdit.js
  client/src/components/Mypage/MypageHeader.js
  client/src/components/Mypage/MypageMain.js
  client/src/components/QuestionCreate/CreateHeader.js
  client/src/components/QuestionCreate/QuesCreateMain.js
  client/src/components/QuestionView/Answer.js
  client/src/components/QuestionView/AnswerCreate.js
  client/src/components/QuestionView/QuestionView.js
  client/src/components/QuestionsList/QuesSearch.js
  client/src/components/QuestionsList/QuestionList.js
  client/src/components/QuestionsList/QuestionsHeader.js
  client/src/components/QuestionsList/QuestionsMain.js
  client/src/components/QuestionsList/Questionsfilter.js
  client/src/components/Shared/CommentCreate.js
  client/src/components/Shared/Commentlist.js
  client/src/components/Shared/DetailView.js
  client/src/components/Shared/TitleHeader.js
Labels: FE

#44 [Client] :art: style: 카드 반응형 css 수정
  client/src/App.js
  client/src/assets/images/ranklogo1.png
  client/src/assets/images/ranklogo2.png
  client/src/assets/images/ranklogo3.png
  client/src/assets/images/top3.png
  client/src/components/Boast/Card.js
  client/src/components/Members/AnswerBox.js
  client/src/components/Members/LevelBox.js
  client/src/components/Members/QuestionBox.js
  client/src/components/Shared/HorizonLine.js
  client/src/components/Shared/MediumButton.js
  client/src/components/Shared/SelectButton.js
  client/src/components/StudyView/StudyViewButtons.js
  client/src/components/layout/Header/HeaderMenu.js
  client/src/pages/Boast.js
  client/src/pages/BoastDetail.js
  client/src/pages/Members.js
  client/src/pages/Reference.js
Labels: FE

#47 [Client]♻️refactor:리팩토링,✨ feat: ToastUi 설치 및 구현, 🎨 style:CSS수정
  client/src/App.js
  client/src/components/Boast/BoastView.js
  client/src/components/Create/Create.js
  client/src/components/Mypage/Mypage.js
  client/src/components/Mypage/MypageEdit.js
  client/src/components/Mypage/MypageMain.js
  client/src/components/QuestionCreate/CreateHeader.js
  client/src/components/QuestionCreate/QuesCreateMain.js
  client/src/components/QuestionView/Answer.js
  client/src/components/QuestionView/AnswerCreate.js
  client/src/components/QuestionView/QuestionViewMain.js
  client/src/components/QuestionsList/QuesSearch.js
  client/src/components/QuestionsList/QuestionList.js
  client/src/components/QuestionsList/Questionsfilter.js
  client/src/components/Shared/CommentCreate.js
  client/src/components/Shared/Commentlist.js
  client/src/components/Shared/DetailView.js
  client/src/components/Shared/TitleHeader.js
  client/src/pages/Mypage.js
  client/src/pages/MypageEdit.js
Labels: FE

#50 [Server] ♻️ refactor: 코드 리팩토링
  server/src/main/generated/seb40main026/mainproject/answer/mapper/AnswerMapperImpl.java
  server/src/main/generated/seb40main026/mainproject/question/mapper/QuestionMapperImpl.java
  server/src/main/generated/seb40main026/mainproject/study/mapper/StudyMapperImpl.java
  server/src/main/java/seb40main026/mainproject/answer/controller/AnswerController.java
  server/src/main/java/seb40main026/mainproject/answer/dto/AnswerDto.java
  server/src/main/java/seb40main026/mainproject/answer/entity/Answer.java
  server/src/main/java/seb40main026/mainproject/answer/mapper/AnswerMapper.java
  server/src/main/java/seb40main026/mainproject/answer/repository/AnswerRepository.java
  server/src/main/java/seb40main026/mainproject/answer/service/AnswerService.java
  server/src/main/java/seb40main026/mainproject/question/controller/QuestionController.java
  server/src/main/java/seb40main026/mainproject/question/controller/QuestionLikeController.java
  server/src/main/java/seb40main026/mainproject/question/controller/QuestionReportController.java
  server/src/main/java/seb40main026/mainproject/question/dto/QuestionDto.java
  server/src/main/java/seb40main026/mainproject/question/dto/QuestionLikeResponseDto.java
  server/src/main/java/seb40main026/mainproject/question/dto/QuestionReportResponseDto.java
  server/src/main/java/seb40main026/mainproject/question/entity/Question.java
  server/src/main/java/seb40main026/mainproject/question/entity/QuestionLike.java
  server/src/main/java/seb40main026/mainproject/question/entity/QuestionReport.java
  server/src/main/java/seb40main026/mainproject/question/mapper/QuestionMapper.java
  server/src/main/java/seb40main026/mainproject/question/repository/QuestionRepository.java
  server/src/main/java/seb40main026/mainproject/question/service/QuestionLikeService.java
  server/src/main/java/seb40main026/mainproject/question/service/QuestionReportService.java
  server/src/main/java/seb40main026/mainproject/question/service/QuestionService.java
  server/src/main/java/seb40main026/mainproject/study/controller/StudyController.java
  server/src/main/java/seb40main026/mainproject/study/dto/StudyDto.java
  server/src/main/java/seb40main026/mainproject/study/entity/Study.java
  server/src/main/java/seb40main026/mainproject/study/mapper/StudyMapper.java
  server/src/main/java/seb40main026/mainproject/study/repository/StudyRepository.java
  server/src/main/java/seb40main026/mainproject/study/service/StudyService.java
Labels: BE

#67 [Server] ✨ feat: 방명록 기능 구현
  server/src/main/generated/seb40main026/mainproject/guestBook/mapper/GuestBookMapperImpl.java
  server/src/main/java/seb40main026/mainproject/exception/ExceptionCode.java
  server/src/main/java/seb40main026/mainproject/guestBook/controller/GuestBookController.java
  server/src/main/java/seb40main026/mainproject/guestBook/dto/GuestBookDto.java
  server/src/main/java/seb40main026/mainproject/guestBook/entity/GuestBook.java
  server/src/main/java/seb40main026/mainproject/guestBook/mapper/GuestBookMapper.java
  server/src/main/java/seb40main026/mainproject/guestBook/repository/GuestBookRepository.java
  server/src/main/java/seb40main026/mainproject/guestBook/service/GuestBookService.java
  server/src/main/java/seb40main026/mainproject/image/controller/imageController.java
  server/src/main/java/seb40main026/mainproject/image/service/ImageService.java
  server/src/main/java/seb40main026/mainproject/study/entity/Study.java
  server/src/main/java/seb40main026/mainproject/study/service/StudyService.java
Labels: BE

#72 [Client]✨feat:질문 조회 및 생성, 답변 조회 및 생성 서버 연결 작업,토큰 파싱
  client/package-lock.json
  client/package.json
  client/src/App.css
  client/src/App.js
  client/src/components/Create/Create.js
  client/src/components/Mypage/MypageEdit.js
  client/src/components/Mypage/MypageMain.js
  client/src/components/Mypage/Token.js
  client/src/components/QuestionCreate/QuesCreateMain.js
  client/src/components/QuestionView/Answer.js
  client/src/components/QuestionView/AnswerCreate.js
  client/src/components/QuestionView/QuestionView.js
  client/src/components/QuestionView/QuestionViewMain.js
  client/src/components/QuestionsList/QuesSearch.js
  client/src/components/QuestionsList/QuestionList.js
  client/src/components/QuestionsList/QuestionsMain.js
  client/src/components/QuestionsList/Questionsfilter.js
  client/src/components/Shared/Commentlist.js
  client/src/components/Shared/DetailView.js
  client/src/components/Shared/LikeButton.js
  client/src/components/Shared/TitleHeader.js
  client/src/components/layout/Header/Header.js
  client/src/components/layout/Header/HeaderLogo.js
  client/src/components/layout/Header/HeaderMenu.js
  client/src/index.js
  client/src/styles/GlobalStyle.js
  client/src/styles/NanumGothic.woff
Labels: FE

#69 [Server] ♻️ refactor: 방명록 작성자 수정
  server/src/main/java/seb40main026/mainproject/exception/ExceptionCode.java
  server/src/main/java/seb40main026/mainproject/guestBook/controller/GuestBookController.java
  server/src/main/java/seb40main026/mainproject/guestBook/entity/GuestBook.java
  server/src/main/java/seb40main026/mainproject/guestBook/mapper/GuestBookMapper.java
  server/src/main/java/seb40main026/mainproject/guestBook/service/GuestBookService.java
Labels: BE

#75 [Client] 🐛fix:jwt_decode 에러 fix,♻️refactor:불필요한 토큰 삭제,✨feat:더보기 기능 추가,mypage/회원정보 수정 페이지 서버 연결작업,🎨 style:CSS수정
  client/package-lock.json
  client/package.json
  client/src/components/Mypage/Mypage.js
  client/src/components/Mypage/MypageEdit.js
  client/src/components/Mypage/MypageMain.js
  client/src/components/QuestionView/Answer.js
  client/src/components/QuestionView/AnswerCreate.js
  client/src/components/QuestionView/QuestionView.js
  client/src/components/QuestionView/QuestionViewMain.js
  client/src/components/QuestionsList/QuesSearch.js
  client/src/components/QuestionsList/QuestionList.js
  client/src/components/Shared/CommentCreate.js
  client/src/components/Shared/Commentlist.js
  client/src/components/Shared/DetailView.js
  client/src/styles/GlobalStyle.js
Labels: FE
